<a href="https://colab.research.google.com/github/Abdallahmoha277/DataWrangling-Kiwilytics/blob/main/Kiwilytics_DataWrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
b = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
print(b)


c=b[2:4,0:2]
print("\n\n",c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


 [[11 12]
 [16 17]]


# New Section

In [5]:
import pandas as pd

monthly_Revenue = pd.Series([3000,5000,4500,np.nan,6000], name = 'Revenue')
print(monthly_Revenue)

0    3000.0
1    5000.0
2    4500.0
3       NaN
4    6000.0
Name: Revenue, dtype: float64


In [6]:
df = {
    'Names' : ['Abdallah','Mohammed','Abdallah','Adam'],
    'Comapny' :['Apple','google','Amazon','OpenAi'],
    'Years_of_experince' : [9,4,5,6]
}
df =pd.DataFrame(df)
print(df)

      Names Comapny  Years_of_experince
0  Abdallah   Apple                   9
1  Mohammed  google                   4
2  Abdallah  Amazon                   5
3      Adam  OpenAi                   6


In [7]:
print(df.head(3))
print("\n\n")
print(df.tail(2))
print("\n\n")

      Names Comapny  Years_of_experince
0  Abdallah   Apple                   9
1  Mohammed  google                   4
2  Abdallah  Amazon                   5



      Names Comapny  Years_of_experince
2  Abdallah  Amazon                   5
3      Adam  OpenAi                   6





In [8]:
print("\n\n")
print(df.info)
print("\n\n")
df.info()




<bound method DataFrame.info of       Names Comapny  Years_of_experince
0  Abdallah   Apple                   9
1  Mohammed  google                   4
2  Abdallah  Amazon                   5
3      Adam  OpenAi                   6>



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Names               4 non-null      object
 1   Comapny             4 non-null      object
 2   Years_of_experince  4 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [9]:
df.describe()


Years_of_experince
count            4.000000
mean             6.000000
std              2.160247
min              4.000000
25%              4.750000
50%              5.500000
75%              6.750000
max              9.000000

In [10]:
print(df.isna().sum())

Names                 0
Comapny               0
Years_of_experince    0
dtype: int64


In [11]:
print(df.isna())

   Names  Comapny  Years_of_experince
0  False    False               False
1  False    False               False
2  False    False               False
3  False    False               False


In [12]:
import numpy as np
df.loc[1, 'Years_of_experince' ] = np.nan
print(df)
print(df.isna().sum())
print(df.dropna())

      Names Comapny  Years_of_experince
0  Abdallah   Apple                 9.0
1  Mohammed  google                 NaN
2  Abdallah  Amazon                 5.0
3      Adam  OpenAi                 6.0
Names                 0
Comapny               0
Years_of_experince    1
dtype: int64
      Names Comapny  Years_of_experince
0  Abdallah   Apple                 9.0
2  Abdallah  Amazon                 5.0
3      Adam  OpenAi                 6.0


In [13]:
df = {
    'Names' : ['Abdallah','Mohammed','Abdallah','Adam'],
    'Comapny' :['Apple','google','Amazon','OpenAi'],
    'Years_of_experince' : [9,4,5,6]
}
df =pd.DataFrame(df)
print(df)

      Names Comapny  Years_of_experince
0  Abdallah   Apple                   9
1  Mohammed  google                   4
2  Abdallah  Amazon                   5
3      Adam  OpenAi                   6


In [14]:
print(df[['Names','Comapny']])
print("\n\n",df.iloc[2])

      Names Comapny
0  Abdallah   Apple
1  Mohammed  google
2  Abdallah  Amazon
3      Adam  OpenAi


 Names                 Abdallah
Comapny                 Amazon
Years_of_experince           5
Name: 2, dtype: object


In [15]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Omar"],
    "Age": [23, 21, 25]
}

# نغير الـ index لأسامي نصية
data = pd.DataFrame(data, index=["i love Melbourne", "student_2", "student_3"])
print(data)


print(data.loc["i love Melbourne"])




                  Name  Age
i love Melbourne   Ali   23
student_2         Sara   21
student_3         Omar   25
Name    Ali
Age      23
Name: i love Melbourne, dtype: object


In [16]:
print(df[df['Years_of_experince'] > 5])

      Names Comapny  Years_of_experince
0  Abdallah   Apple                   9
3      Adam  OpenAi                   6


In [17]:
print(df[df['Comapny']=='Apple'])

      Names Comapny  Years_of_experince
0  Abdallah   Apple                   9


In [18]:
df['Comapny'] = df['Comapny'].str.lower()
print(df)


      Names Comapny  Years_of_experince
0  Abdallah   apple                   9
1  Mohammed  google                   4
2  Abdallah  amazon                   5
3      Adam  openai                   6


In [19]:
df['Is_Very_Seior'] = df['Years_of_experince'] >=5
print(df)

      Names Comapny  Years_of_experince  Is_Very_Seior
0  Abdallah   apple                   9           True
1  Mohammed  google                   4          False
2  Abdallah  amazon                   5           True
3      Adam  openai                   6           True


In [20]:
from os import pidfd_open
df_project = pd.DataFrame({
    'Client' : ['Kiwilytics', 'PwC', 'EY', 'KPMG', 'McKinsey'],
    'Budget_kUSD': [120, 200, np.nan, 150, None]
})

print(df_project,'\n\n')

mean_budget = df_project['Budget_kUSD'].mean()
print(mean_budget)

df_project['Budget_kUSD'] = df_project['Budget_kUSD'].fillna(mean_budget)

print(df_project)


       Client  Budget_kUSD
0  Kiwilytics        120.0
1         PwC        200.0
2          EY          NaN
3        KPMG        150.0
4    McKinsey          NaN 


156.66666666666666
       Client  Budget_kUSD
0  Kiwilytics   120.000000
1         PwC   200.000000
2          EY   156.666667
3        KPMG   150.000000
4    McKinsey   156.666667


In [21]:
# Revenue per company per quarter
df_revenue = pd.DataFrame({
    'Company': ['Kiwilytics', 'PwC', 'EY', 'KPMG', 'Kiwilytics', 'PwC'],
    'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2'],
    'Revenue_kUSD': [120, 200, 180, 150, 130, 210]
})

print(df_revenue)



      Company Quarter  Revenue_kUSD
0  Kiwilytics      Q1           120
1         PwC      Q1           200
2          EY      Q1           180
3        KPMG      Q1           150
4  Kiwilytics      Q2           130
5         PwC      Q2           210


In [22]:
grouped = df_revenue.groupby('Company')['Revenue_kUSD'].sum()
print(grouped)

Company
EY            180
KPMG          150
Kiwilytics    250
PwC           410
Name: Revenue_kUSD, dtype: int64


In [23]:
import pandas as pd
df_managers = pd.DataFrame({
    'ManagerId': [1, 2, 3],
    'Name': ['Ibrahim', 'Maher', 'Abdelrahman']
})

df_projects = pd.DataFrame({
    'ProjectId' : [101,102,103],
    'ManagerId' : [1,2,2,],
    'Clients '  :  ['Kiwilytics', 'PwC', 'EY']
})

merged_df = pd.merge(df_managers, df_projects, on='ManagerId', how='inner')
print(merged_df)

   ManagerId     Name  ProjectId    Clients 
0          1  Ibrahim        101  Kiwilytics
1          2    Maher        102         PwC
2          2    Maher        103          EY


In [24]:
from google.colab import files
uploaded = files.upload()


Saving Orders_with_issues1.csv to Orders_with_issues1.csv


In [25]:
import pandas as pd
import numpy as np

df = pd.read_csv("Orders_with_issues1.csv")
print(df.head())

   OrderID CustomerID   OrderDate ShippedDate        ShippingCost ShipCountry  \
0   1000.0       C001  2025-05-17  2025-07-30  -57.25454602444980     Germany   
1   1001.0       C002  2025-01-26  2025-07-30              320.61      Canada   
2   1002.0       C003  2025-03-08  2025-07-30              165.17      Canada   
3   1003.0       C004  2025-03-24  2025-07-30               12.55     Germany   
4   1004.0       C005  2025-04-15  2025-07-30              186.36      Canada   

    ShipCity                 ShippingCompany  
0    Hamburg  Kiwilytics Goods Shipping LLC.  
1   Montreal                   UPS Worldwide  
2  Vancouver                 FedEx Logistics  
3     Munich            Aramex International  
4  Vancouver                 FedEx Logistics  


In [26]:

df = pd.read_csv("Orders_with_issues1.csv")
print(df.info(100))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   OrderID          239 non-null    float64
 1   CustomerID       240 non-null    object 
 2   OrderDate        237 non-null    object 
 3   ShippedDate      219 non-null    object 
 4   ShippingCost     231 non-null    object 
 5   ShipCountry      245 non-null    object 
 6   ShipCity         241 non-null    object 
 7   ShippingCompany  245 non-null    object 
dtypes: float64(1), object(7)
memory usage: 15.4+ KB
None


In [27]:
print(df.isna().sum())

OrderID             6
CustomerID          5
OrderDate           8
ShippedDate        26
ShippingCost       14
ShipCountry         0
ShipCity            4
ShippingCompany     0
dtype: int64


In [28]:
print(df['ShippingCompany'].value_counts())

ShippingCompany
FedEx Logistics                   54
DHL Express                       53
Aramex International              51
UPS Worldwide                     46
Kiwilytics Goods Shipping LLC.    41
Name: count, dtype: int64


In [29]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'], errors='coerce')
df['ShippedDate'] = pd.to_datetime(df['ShippedDate'], errors='coerce')
df['ShippingCost'] = pd.to_numeric(df['ShippingCost'], errors='coerce')
df.loc[df.ShippingCost < 0, 'ShippingCost'] = np.nan
df=df[~(df['OrderDate'].isna() & df['ShippedDate'].isna())]

In [30]:
df['OrderDate'] = df['OrderDate'].fillna(method='ffill')
df['CustomerID'] = df['CustomerID'].fillna("Unknown")
df['ShipCity'] = df['ShipCity'].fillna("Unspecified")

/tmp/ipython-input-1045331880.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['OrderDate'] = df['OrderDate'].fillna(method='ffill')


In [31]:
df['ShipCountry'] = df['ShipCountry'].str.strip().str.title()
df['ShipCity'] = df['ShipCity'].str.strip().str.title()
df['ShippingCompany'] = df['ShippingCompany'].str.strip()

In [32]:
df.loc[df['ShippingCompany'].str.contains("Kiwilytics", na=False), 'ShippingCompany'] = "Kiwilytics Goods Shipping LLC"

In [33]:
df['DeliveryDays'] = df['ShippedDate'] - df['OrderDate']

In [34]:
avg_Shipping_by_company = df.groupby('ShippingCompany')['ShippingCost'].mean()
print(avg_Shipping_by_company)

ShippingCompany
Aramex International             258.805111
DHL Express                      227.237778
FedEx Logistics                  229.768235
Kiwilytics Goods Shipping LLC    245.112162
UPS Worldwide                    261.228571
Name: ShippingCost, dtype: float64


In [35]:
df.to_csv('cleaned_file.csv',index = False)

In [36]:
print(df.head())

   OrderID CustomerID  OrderDate ShippedDate  ShippingCost ShipCountry  \
0   1000.0       C001 2025-05-17  2025-07-30           NaN     Germany   
1   1001.0       C002 2025-01-26  2025-07-30        320.61      Canada   
2   1002.0       C003 2025-03-08  2025-07-30        165.17      Canada   
3   1003.0       C004 2025-03-24  2025-07-30         12.55     Germany   
4   1004.0       C005 2025-04-15  2025-07-30        186.36      Canada   

    ShipCity                ShippingCompany DeliveryDays  
0    Hamburg  Kiwilytics Goods Shipping LLC      74 days  
1   Montreal                  UPS Worldwide     185 days  
2  Vancouver                FedEx Logistics     144 days  
3     Munich           Aramex International     128 days  
4  Vancouver                FedEx Logistics     106 days  


In [37]:
df['DeliveryStatus'] = df['ShippedDate'].apply(lambda x: 'Delivered' if pd.notna(x) else 'Pending')
print(df['DeliveryStatus'].value_counts())

print(df['DeliveryStatus'].value_counts())

DeliveryStatus
Delivered    211
Pending       31
Name: count, dtype: int64
DeliveryStatus
Delivered    211
Pending       31
Name: count, dtype: int64


In [38]:
print(df.columns)


Index(['OrderID', 'CustomerID', 'OrderDate', 'ShippedDate', 'ShippingCost',
       'ShipCountry', 'ShipCity', 'ShippingCompany', 'DeliveryDays',
       'DeliveryStatus'],
      dtype='object')


In [40]:
df.to_csv("Cleaned_orders_final.csv",index=False)

print(df.head())



   OrderID CustomerID  OrderDate ShippedDate  ShippingCost ShipCountry  \
0   1000.0       C001 2025-05-17  2025-07-30           NaN     Germany   
1   1001.0       C002 2025-01-26  2025-07-30        320.61      Canada   
2   1002.0       C003 2025-03-08  2025-07-30        165.17      Canada   
3   1003.0       C004 2025-03-24  2025-07-30         12.55     Germany   
4   1004.0       C005 2025-04-15  2025-07-30        186.36      Canada   

    ShipCity                ShippingCompany DeliveryDays DeliveryStatus  
0    Hamburg  Kiwilytics Goods Shipping LLC      74 days      Delivered  
1   Montreal                  UPS Worldwide     185 days      Delivered  
2  Vancouver                FedEx Logistics     144 days      Delivered  
3     Munich           Aramex International     128 days      Delivered  
4  Vancouver                FedEx Logistics     106 days      Delivered  


In [41]:
print(df['DeliveryStatus'].value_counts())

DeliveryStatus
Delivered    211
Pending       31
Name: count, dtype: int64


In [43]:
print(df['ShipCountry'].value_counts())

ShipCountry
Uk           53
Usa          49
Canada       45
Egypt        41
Germany      38
Palestine    16
Name: count, dtype: int64


In [44]:
print(df['ShipCity'].value_counts())

ShipCity
Liverpool      20
Montreal       19
Giza           18
Manchester     17
London         15
Munich         14
Toronto        13
Cairo          13
Houston        13
Chicago        13
Hamburg        12
Vancouver      12
Gaza           12
New York       12
Los Angeles    11
Berlin         11
Alexandria      9
Unspecified     4
Al Quds         4
Name: count, dtype: int64


In [46]:
print(df['ShippingCompany'].value_counts().head(3))

ShippingCompany
FedEx Logistics         53
DHL Express             52
Aramex International    51
Name: count, dtype: int64
